name: CICD

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make
      - run: ldd --version
#      - uses: actions/upload-artifact@v3
#        with:
#          name: energy_reader
#          path: build/energy_reader
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: energy_reader
#      - uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --acl public-read --follow-symlinks --delete
#        env:
#          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: 'eu-north-1'
        
