name: CICD

on:
  push:
    branches: [ "master" ]
    
jobs:
  build-jenkins-alpine:
    runs-on: ubuntu-20.04
    container:
      image: jenkins/ssh-agent:alpine
    steps:
      - name: Install GCC
        run: apk add build-base
      - name: Check GCC
        run: gcc --version
      - uses: actions/checkout@v3
      - name: make
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: energy_reader-jenkins-alpine
          path: build/energy_reader

  deploy:
    runs-on: ubuntu-latest
    needs: build-jenkins-alpine
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: energy_reader-jenkins-alpine
          path: artifacts
      - run: find .
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: "artifacts"
